services:
  web:
    container_name: web
    build: .
    ports:
      - "8000:8000"
    networks:
      - custom
    environment:
      DATABASE_URL: mongodb://root:password@mongodb:27017
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - mongodb
  
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - custom
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data:/data/db

networks:
  custom:
    driver: bridge
